import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { PieChart, Pie, Cell, Tooltip, ResponsiveContainer, BarChart, Bar, XAxis, YAxis, CartesianGrid } from 'recharts';
import './styles.css';

const COLORS=['#7c5cff','#f59e0b','#32c48d','#ec6d91','#46a3ff','#a78bfa','#e879f9'];
const MONTHS=['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
const CATEGORIES=['Supermercado','Transferencias','Personal','Transporte','Servicios','Salidas','Otros'];
const now=new Date(), today=now.toISOString().slice(0,10), money=v=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(v||0);
const blank={amount:'',category:'Supermercado',description:'',date:today,type:'variable',recurring:false,recurrenceDay:''};

function App(){
 const [authUser,setAuthUser]=useState(null),[authReady,setAuthReady]=useState(false),[year,setYear]=useState(now.getFullYear()),[month,setMonth]=useState(now.getMonth()+1),[expenses,setExpenses]=useState([]),[summary,setSummary]=useState({total:0,months:[],categories:{}}),[budgets,setBudgets]=useState([]),[form,setForm]=useState(blank),[budget,setBudget]=useState({category:'Supermercado',limit:''}),[msg,setMsg]=useState(''),[quick,setQuick]=useState(false),[dark,setDark]=useState(()=>localStorage.getItem('gastitos-theme')==='dark');
 const load=async()=>{try{const [a,b,c]=await Promise.all([fetch(`/api/expenses?year=${year}&month=${month}`),fetch(`/api/summary?year=${year}`),fetch(`/api/budgets?year=${year}&month=${month}`)]);setExpenses(await a.json());setSummary(await b.json());setBudgets(await c.json())}catch{setMsg('No se pudo conectar con la API. Ejecutá npm run dev.')}};
 useEffect(()=>{fetch('/api/auth/me').then(r=>r.json()).then(data=>setAuthUser(data.user)).catch(()=>setAuthUser(null)).finally(()=>setAuthReady(true))},[]);
 useEffect(()=>{if(authUser)load()},[year,month,authUser]);useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('gastitos-theme',dark?'dark':'light')},[dark]);
 const logout=async()=>{await fetch('/api/auth/logout',{method:'POST'});setAuthUser(null)};
 const total=useMemo(()=>expenses.reduce((n,x)=>n+Number(x.amount),0),[expenses]); const fixed=useMemo(()=>expenses.filter(x=>x.type==='fixed').reduce((n,x)=>n+Number(x.amount),0),[expenses]);
 const categories=useMemo(()=>Object.entries(expenses.reduce((a,x)=>({...a,[x.category]:(a[x.category]||0)+Number(x.amount)}),{})).map(([name,value])=>({name,value})),[expenses]);
 const weekly=useMemo(()=>{const names=['Dom','Lun','Mar','Mié','Jue','Vie','Sáb'],arr=names.map(name=>({name,total:0}));expenses.forEach(x=>arr[new Date(`${x.date}T12:00:00`).getDay()].total+=Number(x.amount));return arr},[expenses]);
 if(!authReady)return <div className="auth-shell"><div className="auth-card"><h1>Gastitos</h1><p>Verificando tu sesión...</p></div></div>;
 if(!authUser)return <AuthScreen onAuth={setAuthUser}/>;
 const set=(key,value)=>setForm(x=>({...x,[key]:value}));
 const add=async e=>{e.preventDefault();setMsg('');const r=await fetch('/api/expenses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});if(!r.ok){setMsg((await r.json()).message);return}const d=new Date(`${form.date}T12:00:00`);setMsg(form.recurring?'Gasto recurrente programado.':'Gasto guardado correctamente.');setForm(blank);setQuick(false);if(d.getFullYear()!==year||d.getMonth()+1!==month){setYear(d.getFullYear());setMonth(d.getMonth()+1)}else load()};
 const remove=async id=>{if(window.confirm('¿Eliminar solo este gasto del mes?')){await fetch(`/api/expenses/${id}`,{method:'DELETE'});load()}};
 const removeRecurrence=async id=>{if(window.confirm('¿Eliminar esta recurrencia y todas sus copias mensuales?')){const r=await fetch(`/api/recurrences/${id}`,{method:'DELETE'});if(!r.ok){setMsg((await r.json()).message);return}setMsg('Recurrencia eliminada de todos los meses.');load()}};
 const addBudget=async e=>{e.preventDefault();const r=await fetch('/api/budgets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...budget,year,month})});if(r.ok){setBudget({category:'Supermercado',limit:''});load()}};
 const backup=async()=>{const r=await fetch(`/api/expenses?year=${year}`),data=await r.json(),blob=new Blob([JSON.stringify({version:1,expenses:data},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`gastitos-${year}.json`;a.click();URL.revokeObjectURL(u)};
 const restore=async e=>{const f=e.target.files?.[0];if(!f)return;try{const r=await fetch('/api/import',{method:'POST',headers:{'Content-Type':'application/json'},body:await f.text()});const x=await r.json();setMsg(`${x.imported} gastos importados.`);load()}catch{setMsg('Archivo de copia no válido.')}e.target.value=''};
 const spent=category=>categories.find(x=>x.name===category)?.value||0;
 return <main className="app-shell"><header><div className="brand"><span className="brand-mark">G</span><div><h1>Gastitos</h1><p>Tu plata, más clara.</p></div></div><div className="top-actions"><button className="theme" onClick={()=>setDark(!dark)}>{dark?'☀':'☾'}</button><div className="year-picker"><button onClick={()=>setYear(year-1)}>‹</button><strong>{year}</strong><button onClick={()=>setYear(year+1)}>›</button></div><button className="logout" onClick={logout}>Salir</button></div></header>
 <section className="intro"><div><span className="eyebrow">PANEL DE GASTOS</span><h2>Hola, llevá el control<br/>sin complicarte.</h2><p>Registrá cada gasto y entendé en qué se va tu dinero.</p></div><div className="monthly-total"><span>Gasto total de {MONTHS[month-1]}</span><strong>{money(total)}</strong><small>{expenses.length} movimientos · Fijos: {money(fixed)}</small></div></section>
 <nav className="month-tabs">{MONTHS.map((x,i)=><button key={x} className={month===i+1?'active':''} onClick={()=>setMonth(i+1)}>{x.slice(0,3)}</button>)}</nav>
 <section className="dashboard"><article className="card add-card"><div className="card-title"><span className="icon">＋</span><div><h3>Nuevo gasto</h3><p>Sumá un movimiento a tu mes</p></div></div><ExpenseForm form={form} set={set} submit={add} msg={msg}/></article>
 <article className="card chart-card"><div className="card-heading"><div><h3>¿En qué gastaste?</h3><p>Distribución de {MONTHS[month-1].toLowerCase()}</p></div><span className="badge">{categories.length} categorías</span></div>{categories.length?<><div className="chart-wrap"><ResponsiveContainer width="100%" height={250}><PieChart><Pie data={categories} dataKey="value" nameKey="name" cx="50%" cy="50%" innerRadius={68} outerRadius={98} paddingAngle={3}>{categories.map((x,i)=><Cell key={x.name} fill={COLORS[i%7]}/>)}</Pie><Tooltip formatter={money}/></PieChart></ResponsiveContainer><div className="chart-center"><strong>{money(total)}</strong><span>Total</span></div></div><Legend data={categories}/></>:<Empty text="Todavía no hay gastos"/>}</article>
 <article className="card detail-card"><div className="card-heading"><div><h3>Detalle del mes</h3><p>Fijos y variables</p></div><strong>{money(total)}</strong></div><div className="expense-list">{expenses.length?expenses.map((x,i)=><div className="expense" key={x.id}><span className="expense-dot" style={{background:COLORS[i%7]}}/><div><b>{x.description}{(x.recurring||x.sourceExpenseId)&&<em> Recurrente</em>}</b><small>{x.category} · {x.type==='fixed'?'Fijo':'Variable'} · {new Date(`${x.date}T12:00:00`).toLocaleDateString('es-AR',{day:'numeric',month:'short'})}</small></div><strong>{money(x.amount)}</strong>{(x.recurring||x.sourceExpenseId)&&<button className="stop-repeat" onClick={()=>removeRecurrence(x.id)}>Quitar repetición</button>}<button className="delete" onClick={()=>remove(x.id)}>×</button></div>):<Empty text={`No hay movimientos en ${MONTHS[month-1].toLowerCase()}.`}/>}</div></article></section>
 <section className="budget-section"><div className="section-heading"><div><span className="eyebrow">PRESUPUESTOS</span><h2>Límites para este mes</h2><p>Te avisamos al llegar al 80% de cada categoría.</p></div><form className="budget-form" onSubmit={addBudget}><select value={budget.category} onChange={e=>setBudget({...budget,category:e.target.value})}>{CATEGORIES.map(x=><option key={x}>{x}</option>)}</select><input required min="1" type="number" placeholder="Límite $" value={budget.limit} onChange={e=>setBudget({...budget,limit:e.target.value})}/><button className="primary">Agregar</button></form></div><div className="budgets">{budgets.length?budgets.map(b=>{const p=Math.min(100,spent(b.category)/b.limit*100),state=p>=100?'danger':p>=80?'warning':'';return <div className="budget card" key={b.id}><div><b>{b.category}</b><button className="delete" onClick={async()=>{await fetch(`/api/budgets/${b.id}`,{method:'DELETE'});load()}}>×</button></div><strong>{money(spent(b.category))} <span>de {money(b.limit)}</span></strong><div className="progress"><i className={state} style={{width:`${p}%`}}/></div><small className={`${state}-text`}>{p>=100?'Límite alcanzado':p>=80?'Atención: más del 80%':`${Math.round(p)}% utilizado`}</small></div>}):<div className="card empty-budget">Creá un límite para controlar mejor tus gastos.</div>}</div></section>
 <section className="annual-section"><div className="section-heading"><div><span className="eyebrow">ANÁLISIS</span><h2>Tu año en números</h2><p>Compará tus gastos semanales y mensuales.</p></div><div className="annual-number"><span>Total anual</span><strong>{money(summary.total)}</strong></div></div><div className="annual-grid"><Graph title="Gastos por semana" data={weekly} color="#32c48d"/><Graph title="Gastos por mes" data={summary.months.map(x=>({...x,name:MONTHS[x.month-1].slice(0,3)}))} color="#7c5cff"/></div></section>
 <section className="backup"><div><b>Copias de seguridad</b><span>Exportá tus datos o recuperalos desde un JSON.</span></div><div><button onClick={backup}>Exportar JSON</button><label className="import">Importar JSON<input type="file" accept="application/json" onChange={restore}/></label></div></section><button className="fab" onClick={()=>setQuick(true)}>＋</button>{quick&&<div className="modal-backdrop" onClick={()=>setQuick(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setQuick(false)}>×</button><h2>Gasto rápido</h2><ExpenseForm form={form} set={set} submit={add} compact/></div></div>}</main>
}
function AuthScreen({onAuth}){const [mode,setMode]=useState('login'),[form,setForm]=useState({name:'',email:'',password:''}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setMessage('');setBusy(true);try{const r=await fetch(`/api/auth/${mode}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}),data=await r.json();if(!r.ok){setMessage(data.message||'No se pudo completar la operación.');return}onAuth(data.user)}catch{setMessage('No se pudo conectar con la API.')}finally{setBusy(false)}};return <main className="auth-shell"><div className="auth-card"><div className="brand"><span className="brand-mark">G</span><div><h1>Gastitos</h1><p>Tu plata, más clara.</p></div></div><h2>{mode==='login'?'Iniciar sesión':'Crear cuenta'}</h2><form onSubmit={submit}>{mode==='register'&&<label>Nombre<input required minLength="2" maxLength="80" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>}<label>Correo electrónico<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Contraseña<input required minLength="8" maxLength="128" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><button className="primary" disabled={busy}>{mode==='login'?'Entrar':'Registrarme'} <span>→</span></button>{message&&<p className="form-message">{message}</p>}</form><button className="auth-switch" onClick={()=>{setMode(mode==='login'?'register':'login');setMessage('')}}>{mode==='login'?'Crear una cuenta':'Ya tengo una cuenta'}</button></div></main>}
function ExpenseForm({form,set,submit,msg,compact}){return <form onSubmit={submit} className={compact?'compact-form':''}><label>Monto<AmountInput value={form.amount} onChange={value=>set('amount',value)} compact={compact}/></label><label>Categoría<select value={form.category} onChange={e=>set('category',e.target.value)}>{CATEGORIES.map(x=><option key={x}>{x}</option>)}</select></label><label>Tipo<div className="type-switch"><button type="button" className={form.type==='variable'?'chosen':''} onClick={()=>set('type','variable')}>Variable</button><button type="button" className={form.type==='fixed'?'chosen':''} onClick={()=>set('type','fixed')}>Fijo</button></div></label>{!compact&&<label>Descripción <span>(opcional)</span><input value={form.description} onChange={e=>set('description',e.target.value)} placeholder="Ej. Compra semanal"/></label>}<label>Fecha<input required type="date" value={form.date} onChange={e=>set('date',e.target.value)}/></label>{!compact&&<><label className="check"><input type="checkbox" checked={form.recurring} onChange={e=>set('recurring',e.target.checked)}/> Repetir cada mes</label>{form.recurring&&<label>Día de cobro<input type="number" min="1" max="31" value={form.recurrenceDay} onChange={e=>set('recurrenceDay',e.target.value)} placeholder="Usar fecha elegida"/></label>}</>}<button className="primary">Guardar gasto <span>→</span></button>{msg&&<p className="form-message">{msg}</p>}</form>}
function AmountInput({value,onChange,compact}){const formatted=value?`$ ${Number(value).toLocaleString('es-AR')}`:'';return <input required autoFocus={compact} className="amount-input" type="text" inputMode="numeric" placeholder="$ 0" value={formatted} onChange={e=>onChange(e.target.value.replace(/\D/g,''))}/>}
function Legend({data}){return <div className="legend">{data.map((x,i)=><div key={x.name}><i style={{background:COLORS[i%7]}}/><span>{x.name}</span><b>{money(x.value)}</b></div>)}</div>};function Empty({text}){return <p className="empty">{text}</p>};function Graph({title,data,color}){return <article className="card annual-chart"><h3>{title}</h3><ResponsiveContainer width="100%" height={230}><BarChart data={data}><CartesianGrid vertical={false} stroke="#eef0f6"/><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis hide/><Tooltip formatter={money}/><Bar dataKey="total" fill={color} radius={[7,7,0,0]}/></BarChart></ResponsiveContainer></article>};createRoot(document.getElementById('root')).render(<App/>);
